In [17]:
import numpy as np
import pandas as pd
a={
    1:[3,6],
    2:[4,5],
    3:[4,3],
    4:[5,1],
    5:[1,0]
}

print("Initial dict",a)




Initial dict {1: [3, 6], 2: [4, 5], 3: [4, 3], 4: [5, 1], 5: [1, 0]}


In [23]:
# a_df=pd.DataFrame(list(a.items()))
a_df=pd.DataFrame.from_dict(a,orient='index')
print(a_df)

   0  1
1  3  6
2  4  5
3  4  3
4  5  1
5  1  0


In [24]:
a_df.sort_values(by=[0,1],ascending=[True,False],inplace=True)
print(a_df)

   0  1
5  1  0
1  3  6
2  4  5
3  4  3
4  5  1


In [13]:
import numpy as np

a=np.array([ [1,3,6],
            [2,4,2],
            [3,4,6],
            [4,4,3]
            ])
print(a)

[[1 3 6]
 [2 4 2]
 [3 4 6]
 [4 4 3]]


In [15]:
a

array([[1, 3, 6],
       [2, 4, 2],
       [3, 4, 6],
       [4, 4, 3]])